name: Check code on pull requests & subsequent pushes

on:
  pull_request:
    branches:
      - staging

jobs:
  tests:
    name: tests
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install unittest pylint
      - name: lint
        run: pylint ./src
      - name: Test
        run: python -m unittest discover -s tests